### PR TITLE
Modified link so multiple react components can instantiate different …

### PR DESCRIPTION
**Pull request by jlaramie**
…plaid links

### CODE REVIEW

**Comment by pbernasconi** [comment]
Hey @jlaramie - this PR seems to have merge conflicts after the recent changes – would you mind updating this PR?

**Comment by jlaramie** [comment]
I'll look into getting that fixed today

**Comment by andrewholsted** [comment]
@pbernasconi - Were there still merge conflicts on this? I ran into a similar issue earlier today and came here looking for a workaround.

**Comment by jlaramie** [comment]
Yeah I need to reimplement it off current master. They're are just too many
changes to merge.

**Pull request closed without merging**
